/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    categories: Category;
    products: Product;
    productVariants: ProductVariant;
    carts: Cart;
    'cart-items': CartItem;
    orders: Order;
    'order-items': OrderItem;
    payments: Payment;
    'payment-options': PaymentOption;
    addresses: Address;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    productVariants: ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'cart-items': CartItemsSelect<false> | CartItemsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'payment-options': PaymentOptionsSelect<false> | PaymentOptionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  phone?: string | null;
  dateOfBirth?: string | null;
  gender?: ('male' | 'female' | 'other' | 'not_specified') | null;
  /**
   * Deactivate to prevent customer from logging in
   */
  isActive?: boolean | null;
  /**
   * Internal notes about this customer
   */
  customerNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Unique identifier for the category URL
   */
  slug: string;
  /**
   * Select a parent category to create a subcategory
   */
  parent?: (string | null) | Category;
  description?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  variants?: (number | ProductVariant)[] | null;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: string | Category;
  /**
   * Publish this product on the storefront
   */
  isActive?: boolean | null;
  /**
   * Show this product in featured sections
   */
  featured?: boolean | null;
  'product-variant'?:
    | {
        variant?: string | null;
        /**
         * Stock Keeping Unit - unique identifier
         */
        sku: string;
        /**
         * Current selling price
         */
        price: number;
        /**
         * Show as strikethrough if different from current price
         */
        oldPrice?: number | null;
        /**
         * Your cost for this variant (internal use)
         */
        cost?: number | null;
        stockQuantity: number;
        /**
         * Get notified when stock falls below this number
         */
        lowStockThreshold?: number | null;
        /**
         * Product weight for shipping calculations
         */
        weight?: number | null;
        dimensions?: {
          length?: number | null;
          width?: number | null;
          height?: number | null;
        };
        /**
         * Specific image for this variant
         */
        image?: (string | null) | Media;
        /**
         * Make this variant available for purchase
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main product image displayed in listings
   */
  thumbnail: string | Media;
  /**
   * Additional product images
   */
  gallery?:
    | {
        image: string | Media;
        /**
         * Describe the image for accessibility and SEO
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Override default title for SEO (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Meta description for search engines (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Keywords for internal search and categorization
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Specify if this content exists elsewhere to avoid duplicate content issues
     */
    canonicalUrl?: string | null;
    /**
     * Title when shared on social media (defaults to Meta Title)
     */
    ogTitle?: string | null;
    /**
     * Description when shared on social media (defaults to Meta Description)
     */
    ogDescription?: string | null;
    /**
     * Image when shared on social media (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
    ogType?: ('product' | 'article' | 'website') | null;
    twitterCard?: ('summary' | 'summary_large_image' | 'product') | null;
    /**
     * Title for Twitter (defaults to OG Title or Meta Title)
     */
    twitterTitle?: string | null;
    /**
     * Description for Twitter (defaults to OG Description or Meta Description)
     */
    twitterDescription?: string | null;
    /**
     * Image for Twitter (defaults to OG Image)
     */
    twitterImage?: (string | null) | Media;
    /**
     * Product brand name for structured data
     */
    brand?: string | null;
    /**
     * Global Trade Item Number (UPC, EAN, ISBN)
     */
    gtin?: string | null;
    /**
     * Manufacturer Part Number
     */
    mpn?: string | null;
    condition?: ('new' | 'refurbished' | 'used') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants".
 */
export interface ProductVariant {
  id: number;
  variant?: string | null;
  /**
   * Stock Keeping Unit - unique identifier
   */
  sku: string;
  /**
   * Current selling price
   */
  price: number;
  /**
   * Show as strikethrough if different from current price
   */
  oldPrice?: number | null;
  /**
   * Your cost for this variant (internal use)
   */
  cost?: number | null;
  stockQuantity: number;
  /**
   * Get notified when stock falls below this number
   */
  lowStockThreshold?: number | null;
  /**
   * Product weight for shipping calculations
   */
  weight?: number | null;
  dimensions?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  /**
   * Specific image for this variant
   */
  image?: (string | null) | Media;
  /**
   * Make this variant available for purchase
   */
  isActive?: boolean | null;
  product?: (string | null) | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  /**
   * Associated customer (for logged-in customers)
   */
  customer?: (string | null) | Customer;
  /**
   * Session identifier for guest users
   */
  sessionId?: string | null;
  /**
   * Automatic cart cleanup date
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items".
 */
export interface CartItem {
  id: string;
  cart: string | Cart;
  product: string | Product;
  variant: string;
  quantity: number;
  /**
   * Price at the time of adding to cart
   */
  price: number;
  /**
   * Calculated as quantity × price
   */
  subtotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order identifier
   */
  orderNumber: string;
  /**
   * Registered customer (if logged in)
   */
  customer?: (string | null) | Customer;
  /**
   * For guest checkout
   */
  guestName?: string | null;
  guestEmail?: string | null;
  guestPhone?: string | null;
  shippingAddress: {
    recipientName: string;
    phone: string;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    province: string;
    postalCode: string;
  };
  orderStatus: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * Total order amount
   */
  totalAmount: number;
  shippingCost?: number | null;
  discount?: number | null;
  /**
   * Internal notes or customer comments
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: string | Order;
  product: string | Product;
  variant: string;
  /**
   * Stored product details at time of purchase
   */
  productSnapshot?: {
    title?: string | null;
    variantTitle?: string | null;
    sku?: string | null;
    imageUrl?: string | null;
  };
  quantity: number;
  /**
   * Price at the time of purchase
   */
  price: number;
  /**
   * Calculated as quantity × price
   */
  subtotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  order: string | Order;
  method: 'credit_card' | 'bank_transfer' | 'cod' | 'e_wallet' | 'paypal' | 'stripe' | 'other';
  /**
   * Payment gateway transaction identifier
   */
  transactionId?: string | null;
  status: 'pending' | 'processing' | 'success' | 'failed' | 'refunded' | 'cancelled';
  amount: number;
  /**
   * Currency code (e.g., USD, EUR, IDR)
   */
  currency?: string | null;
  /**
   * Raw response from payment gateway (JSON format)
   */
  gatewayResponse?: string | null;
  /**
   * Additional payment notes or details
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-options".
 */
export interface PaymentOption {
  id: number;
  /**
   * e.g., "Credit Card", "Bank Transfer BCA"
   */
  name: string;
  type: 'credit_card' | 'bank_transfer' | 'cod' | 'e_wallet' | 'paypal' | 'stripe';
  /**
   * Additional information about this payment method
   */
  description?: string | null;
  icon?: (string | null) | Media;
  /**
   * Enable or disable this payment option
   */
  isActive?: boolean | null;
  /**
   * Fee percentage for this payment method
   */
  processingFee?: number | null;
  /**
   * Detailed instructions for customers
   */
  instructions?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer: string | Customer;
  /**
   * e.g., "Home", "Office", "Mom's House"
   */
  label: string;
  recipientName: string;
  phone: string;
  /**
   * Street address, P.O. box, company name
   */
  addressLine1: string;
  /**
   * Apartment, suite, unit, building, floor, etc.
   */
  addressLine2?: string | null;
  city: string;
  province: string;
  postalCode: string;
  country?: string | null;
  /**
   * Use this address as the default shipping address
   */
  isDefault?: boolean | null;
  /**
   * Optional location coordinates for delivery
   */
  coordinates?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'productVariants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'cart-items';
        value: string | CartItem;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null)
    | ({
        relationTo: 'payment-options';
        value: number | PaymentOption;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  phone?: T;
  dateOfBirth?: T;
  gender?: T;
  isActive?: T;
  customerNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  id?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  id?: T;
  variants?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  description?: T;
  category?: T;
  isActive?: T;
  featured?: T;
  'product-variant'?:
    | T
    | {
        variant?: T;
        sku?: T;
        price?: T;
        oldPrice?: T;
        cost?: T;
        stockQuantity?: T;
        lowStockThreshold?: T;
        weight?: T;
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
        image?: T;
        isActive?: T;
        id?: T;
      };
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogType?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        brand?: T;
        gtin?: T;
        mpn?: T;
        condition?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productVariants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  variant?: T;
  sku?: T;
  price?: T;
  oldPrice?: T;
  cost?: T;
  stockQuantity?: T;
  lowStockThreshold?: T;
  weight?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  image?: T;
  isActive?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  id?: T;
  customer?: T;
  sessionId?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items_select".
 */
export interface CartItemsSelect<T extends boolean = true> {
  id?: T;
  cart?: T;
  product?: T;
  variant?: T;
  quantity?: T;
  price?: T;
  subtotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  id?: T;
  orderNumber?: T;
  customer?: T;
  guestName?: T;
  guestEmail?: T;
  guestPhone?: T;
  shippingAddress?:
    | T
    | {
        recipientName?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
      };
  orderStatus?: T;
  paymentStatus?: T;
  totalAmount?: T;
  shippingCost?: T;
  discount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  variant?: T;
  productSnapshot?:
    | T
    | {
        title?: T;
        variantTitle?: T;
        sku?: T;
        imageUrl?: T;
      };
  quantity?: T;
  price?: T;
  subtotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  id?: T;
  order?: T;
  method?: T;
  transactionId?: T;
  status?: T;
  amount?: T;
  currency?: T;
  gatewayResponse?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-options_select".
 */
export interface PaymentOptionsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  description?: T;
  icon?: T;
  isActive?: T;
  processingFee?: T;
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  id?: T;
  customer?: T;
  label?: T;
  recipientName?: T;
  phone?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  country?: T;
  isDefault?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage home page content and settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    enabled?: boolean | null;
    /**
     * Main headline for the hero section
     */
    title: string;
    /**
     * Supporting text for the hero section
     */
    subtitle?: string | null;
    /**
     * Hero background image (recommended: 1920x800px)
     */
    backgroundImage?: (string | null) | Media;
    ctaButtons?:
      | {
          text: string;
          /**
           * URL or path (e.g., /products, /about)
           */
          link: string;
          style?: ('primary' | 'secondary' | 'outline') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Rotating banners for promotions and campaigns
   */
  banners?:
    | {
        /**
         * Recommended size: 1920x600px
         */
        image: string | Media;
        title?: string | null;
        description?: string | null;
        /**
         * Where should this banner link to?
         */
        link?: string | null;
        /**
         * Leave empty to hide button
         */
        buttonText?: string | null;
        /**
         * Show/hide this banner
         */
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small promotional banners (e.g., free shipping, discounts)
   */
  promotionalBanners?:
    | {
        /**
         * Small icon (64x64px recommended)
         */
        icon?: (string | null) | Media;
        title: string;
        description?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredProducts?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    displayType?: ('auto' | 'manual') | null;
    /**
     * Only used when Display Type is Manual Selection
     */
    products?: (string | Product)[] | null;
    limit?: number | null;
  };
  newArrivals?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    limit?: number | null;
  };
  categoriesShowcase?: {
    enabled?: boolean | null;
    title?: string | null;
    /**
     * Select categories to highlight on home page
     */
    categories?: (string | Category)[] | null;
  };
  /**
   * Add custom content sections to your home page
   */
  contentBlocks?:
    | {
        type: 'text-image' | 'image-grid' | 'testimonials' | 'newsletter';
        title?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (string | null) | Media;
        layout?: ('left' | 'right' | 'full') | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Page title for SEO (50-60 characters)
     */
    metaTitle?: string | null;
    /**
     * Page description for search engines (150-160 characters)
     */
    metaDescription?: string | null;
    /**
     * Image shown when sharing on social media (1200x630px)
     */
    ogImage?: (string | null) | Media;
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        ctaButtons?:
          | T
          | {
              text?: T;
              link?: T;
              style?: T;
              id?: T;
            };
      };
  banners?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        link?: T;
        buttonText?: T;
        active?: T;
        id?: T;
      };
  promotionalBanners?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        link?: T;
        id?: T;
      };
  featuredProducts?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        displayType?: T;
        products?: T;
        limit?: T;
      };
  newArrivals?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        limit?: T;
      };
  categoriesShowcase?:
    | T
    | {
        enabled?: T;
        title?: T;
        categories?: T;
      };
  contentBlocks?:
    | T
    | {
        type?: T;
        title?: T;
        content?: T;
        image?: T;
        layout?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}