/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    categories: Category;
    media: Media;
    products: Product;
    addresses: Address;
    orders: Order;
    'order-items': OrderItem;
    payments: Payment;
    'payment-options': PaymentOption;
    customers: Customer;
    carts: Cart;
    'cart-items': CartItem;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'payment-options': PaymentOptionsSelect<false> | PaymentOptionsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'cart-items': CartItemsSelect<false> | CartItemsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'store-config': StoreConfig;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'store-config': StoreConfigSelect<false> | StoreConfigSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short description of the post
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  categories?: (string | Category)[] | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Select a parent category to create a subcategory
   */
  parent?: (string | null) | Category;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  defaultVariant?: string | null;
  defaultVariantPrice?: number | null;
  category: string | Category;
  /**
   * Publish this product on the storefront
   */
  isActive?: boolean | null;
  /**
   * Show this product in featured sections
   */
  featured?: boolean | null;
  'product-variant'?:
    | {
        id?: string | null;
        variant?: string | null;
        /**
         * Stock Keeping Unit - unique identifier
         */
        sku: string;
        /**
         * Current selling price
         */
        price: number;
        /**
         * Show as strikethrough if different from current price
         */
        oldPrice?: number | null;
        /**
         * Your cost for this variant (internal use)
         */
        cost?: number | null;
        stockQuantity: number;
        /**
         * Get notified when stock falls below this number
         */
        lowStockThreshold?: number | null;
        /**
         * Product weight for shipping calculations
         */
        weight?: number | null;
        dimensions?: {
          length?: number | null;
          width?: number | null;
          height?: number | null;
        };
        /**
         * Specific image for this variant
         */
        image?: (number | null) | Media;
        /**
         * Make this variant available for purchase
         */
        isActive?: boolean | null;
      }[]
    | null;
  /**
   * Main product image displayed in listings
   */
  thumbnail?: (number | null) | Media;
  /**
   * Additional product images
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Describe the image for accessibility and SEO
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Override default title for SEO (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Meta description for search engines (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Keywords for internal search and categorization
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Specify if this content exists elsewhere to avoid duplicate content issues
     */
    canonicalUrl?: string | null;
    /**
     * Title when shared on social media (defaults to Meta Title)
     */
    ogTitle?: string | null;
    /**
     * Description when shared on social media (defaults to Meta Description)
     */
    ogDescription?: string | null;
    /**
     * Image when shared on social media (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    ogType?: ('product' | 'article' | 'website') | null;
    twitterCard?: ('summary' | 'summary_large_image' | 'product') | null;
    /**
     * Title for Twitter (defaults to OG Title or Meta Title)
     */
    twitterTitle?: string | null;
    /**
     * Description for Twitter (defaults to OG Description or Meta Description)
     */
    twitterDescription?: string | null;
    /**
     * Image for Twitter (defaults to OG Image)
     */
    twitterImage?: (number | null) | Media;
    /**
     * Product brand name for structured data
     */
    brand?: string | null;
    /**
     * Global Trade Item Number (UPC, EAN, ISBN)
     */
    gtin?: string | null;
    /**
     * Manufacturer Part Number
     */
    mpn?: string | null;
    condition?: ('new' | 'refurbished' | 'used') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  sessionId?: string | null;
  customer?: (string | null) | Customer;
  /**
   * e.g., "Home", "Office", "Mom's House"
   */
  label: string;
  recipientName: string;
  phone: string;
  email?: string | null;
  /**
   * Street address, P.O. box, company name
   */
  addressLine1: string;
  /**
   * Apartment, suite, unit, building, floor, etc.
   */
  addressLine2?: string | null;
  city: string;
  province: string;
  postalCode: string;
  country?: string | null;
  /**
   * Use this address as the default shipping address
   */
  isDefault?: boolean | null;
  /**
   * Optional location coordinates for delivery
   */
  coordinates?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  phone?: string | null;
  dateOfBirth?: string | null;
  gender?: ('male' | 'female' | 'other' | 'not_specified') | null;
  /**
   * Deactivate to prevent customer from logging in
   */
  isActive?: boolean | null;
  /**
   * Internal notes about this customer
   */
  customerNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order identifier
   */
  orderNumber: string;
  /**
   * Registered customer (if logged in)
   */
  customer?: (string | null) | Customer;
  /**
   * Session Id for guest user
   */
  sessionId?: string | null;
  /**
   * For guest checkout
   */
  guestName?: string | null;
  guestEmail?: string | null;
  guestPhone?: string | null;
  shippingAddress: {
    recipientName: string;
    phone: string;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    province: string;
    postalCode: string;
    country?: string | null;
  };
  shippingService?: {
    shippingService?: string | null;
    resiNumber?: string | null;
  };
  /**
   * Payment method code from Duitku
   */
  paymentMethod?: string | null;
  /**
   * Payment reference from Duitku
   */
  paymentReference?: string | null;
  /**
   * Virtual Account number (if applicable)
   */
  vaNumber?: string | null;
  orderStatus: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * Total order amount
   */
  totalAmount: number;
  shippingCost?: number | null;
  discount?: number | null;
  /**
   * Internal notes or customer comments
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: string | Order;
  product: string | Product;
  variant: string;
  /**
   * Stored product details at time of purchase
   */
  productSnapshot?: {
    title?: string | null;
    variantTitle?: string | null;
    sku?: string | null;
    imageUrl?: string | null;
  };
  quantity: number;
  /**
   * Price at the time of purchase
   */
  price: number;
  /**
   * Calculated as quantity × price
   */
  subtotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  order: string | Order;
  method: 'credit_card' | 'bank_transfer' | 'cod' | 'e_wallet' | 'paypal' | 'stripe' | 'other';
  /**
   * Payment gateway transaction identifier
   */
  transactionId?: string | null;
  status: 'pending' | 'processing' | 'success' | 'failed' | 'refunded' | 'cancelled';
  amount: number;
  /**
   * Currency code (e.g., USD, EUR, IDR)
   */
  currency?: string | null;
  /**
   * Raw response from payment gateway (JSON format)
   */
  gatewayResponse?: string | null;
  /**
   * Additional payment notes or details
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-options".
 */
export interface PaymentOption {
  id: number;
  /**
   * e.g., "Credit Card", "Bank Transfer BCA"
   */
  name: string;
  type: 'credit_card' | 'bank_transfer' | 'cod' | 'e_wallet' | 'paypal' | 'stripe';
  /**
   * Additional information about this payment method
   */
  description?: string | null;
  icon?: (number | null) | Media;
  /**
   * Enable or disable this payment option
   */
  isActive?: boolean | null;
  /**
   * Fee percentage for this payment method
   */
  processingFee?: number | null;
  /**
   * Detailed instructions for customers
   */
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  /**
   * Associated customer (for logged-in customers)
   */
  customer?: (string | null) | Customer;
  /**
   * Session identifier for guest users
   */
  sessionId?: string | null;
  address?: (string | null) | Address;
  /**
   * Automatic cart cleanup date
   */
  expiresAt?: string | null;
  isDone?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items".
 */
export interface CartItem {
  id: string;
  cart: string | Cart;
  product: string | Product;
  variant: string;
  quantity: number;
  /**
   * Price at the time of adding to cart
   */
  price: number;
  /**
   * Calculated as quantity × price
   */
  subtotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Main image displayed at the top of the page
   */
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  seo?: {
    /**
     * Override the page title for search engines (50-60 characters)
     */
    title?: string | null;
    /**
     * Brief description for search results (150-160 characters)
     */
    description?: string | null;
    /**
     * Comma-separated keywords for search engines
     */
    keywords?: string | null;
    /**
     * Image for social media sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null)
    | ({
        relationTo: 'payment-options';
        value: number | PaymentOption;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'cart-items';
        value: string | CartItem;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  categories?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  slugLock?: T;
  description?: T;
  defaultVariant?: T;
  defaultVariantPrice?: T;
  category?: T;
  isActive?: T;
  featured?: T;
  'product-variant'?:
    | T
    | {
        id?: T;
        variant?: T;
        sku?: T;
        price?: T;
        oldPrice?: T;
        cost?: T;
        stockQuantity?: T;
        lowStockThreshold?: T;
        weight?: T;
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
        image?: T;
        isActive?: T;
      };
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogType?: T;
        twitterCard?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        brand?: T;
        gtin?: T;
        mpn?: T;
        condition?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  id?: T;
  sessionId?: T;
  customer?: T;
  label?: T;
  recipientName?: T;
  phone?: T;
  email?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  country?: T;
  isDefault?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  id?: T;
  orderNumber?: T;
  customer?: T;
  sessionId?: T;
  guestName?: T;
  guestEmail?: T;
  guestPhone?: T;
  shippingAddress?:
    | T
    | {
        recipientName?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        country?: T;
      };
  shippingService?:
    | T
    | {
        shippingService?: T;
        resiNumber?: T;
      };
  paymentMethod?: T;
  paymentReference?: T;
  vaNumber?: T;
  orderStatus?: T;
  paymentStatus?: T;
  totalAmount?: T;
  shippingCost?: T;
  discount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  variant?: T;
  productSnapshot?:
    | T
    | {
        title?: T;
        variantTitle?: T;
        sku?: T;
        imageUrl?: T;
      };
  quantity?: T;
  price?: T;
  subtotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  id?: T;
  order?: T;
  method?: T;
  transactionId?: T;
  status?: T;
  amount?: T;
  currency?: T;
  gatewayResponse?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-options_select".
 */
export interface PaymentOptionsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  description?: T;
  icon?: T;
  isActive?: T;
  processingFee?: T;
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  phone?: T;
  dateOfBirth?: T;
  gender?: T;
  isActive?: T;
  customerNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  id?: T;
  customer?: T;
  sessionId?: T;
  address?: T;
  expiresAt?: T;
  isDone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items_select".
 */
export interface CartItemsSelect<T extends boolean = true> {
  id?: T;
  cart?: T;
  product?: T;
  variant?: T;
  quantity?: T;
  price?: T;
  subtotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  heroImage?: T;
  content?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage home page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    enabled?: boolean | null;
    title: string;
    subtitle?: string | null;
    image?: (number | null) | Media;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
  };
  promotions?:
    | {
        icon?: (number | null) | Media;
        title: string;
        description?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredProducts?: {
    enabled?: boolean | null;
    title?: string | null;
    selectionMode?: ('auto' | 'manual') | null;
    products?: (string | Product)[] | null;
    limit?: number | null;
  };
  newArrivals?: {
    enabled?: boolean | null;
    title?: string | null;
    limit?: number | null;
  };
  categoriesShowcase?: {
    enabled?: boolean | null;
    title?: string | null;
    categories?: (string | Category)[] | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Master configuration for branding, localization, and SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-config".
 */
export interface StoreConfig {
  id: number;
  storeName: string;
  storeOwner?: string | null;
  logo: number | Media;
  favicon?: (number | null) | Media;
  storeDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  defaultCurrency?: ('IDR' | 'USD') | null;
  currencySymbol?: string | null;
  weightClass?: ('kg' | 'g') | null;
  lengthClass?: ('cm' | 'mm') | null;
  /**
   * Flat rate for shipping
   */
  defaultShippingCost?: number | null;
  /**
   * Minimum spend for free shipping
   */
  freeShippingThreshold?: number | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  socialLinks?:
    | {
        platform?: ('Instagram' | 'WhatsApp' | 'Facebook' | 'TikTok' | 'Twitter') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The title used by search engines and browser tabs.
   */
  metaTitle?: string | null;
  /**
   * The summary used by search engines (120-160 characters recommended).
   */
  metaDescription?: string | null;
  /**
   * Keywords for search engines to help with discoverability.
   */
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The canonical URL for your site (e.g., https://yourstore.com).
   */
  canonicalUrl?: string | null;
  /**
   * Title for social media sharing (defaults to metaTitle if not set).
   */
  ogTitle?: string | null;
  /**
   * Description for social media sharing (defaults to metaDescription if not set).
   */
  ogDescription?: string | null;
  /**
   * Image shown when sharing the site on Facebook, LinkedIn, etc.
   */
  ogImage?: (number | null) | Media;
  /**
   * Type of Twitter card to use.
   */
  twitterCard?: ('summary' | 'summary_large_image') | null;
  /**
   * Title for Twitter sharing (defaults to ogTitle or metaTitle if not set).
   */
  twitterTitle?: string | null;
  /**
   * Description for Twitter sharing (defaults to ogDescription or metaDescription if not set).
   */
  twitterDescription?: string | null;
  /**
   * Image for Twitter sharing (defaults to ogImage if not set).
   */
  twitterImage?: (number | null) | Media;
  /**
   * Prevent search engines from indexing this site.
   */
  noIndex?: boolean | null;
  /**
   * Prevent search engines from following links on this site.
   */
  noFollow?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        image?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  promotions?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        link?: T;
        id?: T;
      };
  featuredProducts?:
    | T
    | {
        enabled?: T;
        title?: T;
        selectionMode?: T;
        products?: T;
        limit?: T;
      };
  newArrivals?:
    | T
    | {
        enabled?: T;
        title?: T;
        limit?: T;
      };
  categoriesShowcase?:
    | T
    | {
        enabled?: T;
        title?: T;
        categories?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-config_select".
 */
export interface StoreConfigSelect<T extends boolean = true> {
  storeName?: T;
  storeOwner?: T;
  logo?: T;
  favicon?: T;
  storeDescription?: T;
  defaultCurrency?: T;
  currencySymbol?: T;
  weightClass?: T;
  lengthClass?: T;
  defaultShippingCost?: T;
  freeShippingThreshold?: T;
  email?: T;
  phone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  canonicalUrl?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  twitterCard?: T;
  twitterTitle?: T;
  twitterDescription?: T;
  twitterImage?: T;
  noIndex?: T;
  noFollow?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}